blog/blog/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author   : huhu
# @Time     : 2023/3/15 18:32
# @File     : blog_bp.py.py
# @Project  : project_05
# @objective: 

from flask import Flask, request, render_template, redirect, session, flash
from flask import Blueprint, request, render_template, redirect, url_for, flash, send_file
from blog.utils import is_login
import sqlite3
import datetime

# from jinja2 import Markup
from jinja2.utils import markupsafe
from pyecharts import options as opts
from pyecharts.charts import Bar
from create_db import initialization, connect
from blog_06.create_db2 import connect

# 数据库初始化
initialization()

users = [
    {
        'username':'root',
        'password':'root'
    }
]


blog_bp = Blueprint('blog', __name__, url_prefix='/')


# 首页
@blog_bp.route('/')
@is_login
def index():
    conn = sqlite3.connect('blog.db')
    cursor = conn.cursor()
    # conn, cursor = connect()
    # 查询所有文章
    cursor.execute('SELECT id, title, content, created_at FROM posts ORDER BY created_at DESC')
    posts = cursor.fetchall()
    posts = [{'id': id, 'title': title, 'content': content, 'created_at': created_at} for id, title, content, created_at in posts]

    # 渲染模板
    return render_template('index.html', posts=posts)


# @blog_bp.route('/index_01')
# def index_01():
#     # 渲染模板
#     return send_file(r'../templates/base.html')


@blog_bp.route('/biaoge')
def biaoge():
    conn = sqlite3.connect('blog.db')
    cursor = conn.cursor()

    # 查询所有文章
    cursor.execute('SELECT id, title, content, created_at FROM posts ORDER BY created_at DESC')
    posts = cursor.fetchall()
    posts = [{'id': id, 'title': title, 'content': content, 'created_at': created_at} for id, title, content, created_at in posts]

    # 渲染模板
    return render_template('biaoge.html', posts=posts)

# 按文章标题查询文章内容，后台是按文章 ID 查询的，此页面有编辑文章按钮与删除文章按钮
@blog_bp.route('/<int:id>')
@is_login
def show(id):
    conn = sqlite3.connect('blog.db')
    cursor = conn.cursor()

    # 查询文章
    cursor.execute('SELECT id, title, content, created_at, updated_at FROM posts WHERE id = ?', (id,))
    post = cursor.fetchone()
    if post is None:
        return '404 Not Found'
    post = {'id': post[0], 'title': post[1], 'content': post[2], 'created_at': post[3], 'updated_at': post[4]}

    # 渲染模板
    return render_template('show.html', post=post)

# # 查询
# @blog_bp.route('/<title>' ,methods=['GET', 'POST'])
# @is_login
# def find(title):
#     conn = sqlite3.connect('blog.db')
#     cursor = conn.cursor()
#
#     # 查询文章
#     cursor.execute('SELECT id, title, content, created_at, updated_at FROM posts WHERE title = ?', (title,))
#     post = cursor.fetchone()
#     if post is None:
#         return '404 Not Found'
#     post = {'id': post[0], 'title': post[1], 'content': post[2], 'created_at': post[3], 'updated_at': post[4]}
#
#     # 渲染模板
#     return render_template('show.html', post=post)


# 新增文章页面
@blog_bp.route('/create', methods=['GET', 'POST'])
@is_login
def create():
    if request.method == 'POST':
        # 获取表单提交的数据
        title = request.form['title']
        content = request.form['content']
        created_at = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        updated_at = created_at

        # 插入文章
        conn = sqlite3.connect('blog.db')
        cursor = conn.cursor()
        cursor.execute('INSERT INTO posts (title, content, created_at, updated_at) VALUES (?, ?, ?, ?)', (title, content, created_at, updated_at))
        conn.commit()
        conn.close()

        # 显示成功消息
        flash('文章已添加')
        return redirect(url_for('blog.index'))

    # 渲染模板
    return render_template('create.html')

@blog_bp.route('/chaxun', methods=['GET', 'POST'])
@is_login
def find():
    if request.method == 'POST':
        # 获取表单提交的数据
        title = request.form['title']

        # 查询文章
        conn = sqlite3.connect('blog.db')
        cursor = conn.cursor()
        cursor.execute('SELECT id, title, content, created_at, updated_at FROM posts WHERE title = ?', (title,))
        post = cursor.fetchone()
        if post is None:
            return '404 Not Found'
        # post = {'id': post[0], 'title': post[1], 'content': post[2], 'created_at': post[3], 'updated_at': post[4]}

        id = int(post[0])

        return redirect(url_for('blog.show', id=id))


# 从数据库获取文章，并进行更新、编辑
@blog_bp.route('/<int:id>/edit', methods=['GET', 'POST'])
@is_login
def edit(id):
    conn = sqlite3.connect('blog.db')
    cursor = conn.cursor()

    # 查询文章
    cursor.execute('SELECT id, title, content, created_at, updated_at FROM posts WHERE id = ?', (id,))
    post = cursor.fetchone()
    if post is None:
        return '404 Not Found'

    if request.method == 'POST':
        # 获取表单提交的数据
        title = request.form['title']
        content = request.form['content']
        updated_at = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')

        # 更新文章
        cursor.execute('UPDATE posts SET title = ?, content = ?, updated_at = ? WHERE id = ?', (title, content, updated_at, id))
        conn.commit()
        conn.close()

        # 显示成功消息
        flash('文章已更新')
        return redirect(url_for('blog.show', id=id))

    # 渲染模板
    post = {'id': post[0], 'title': post[1], 'content': post[2], 'created_at': post[3], 'updated_at': post[4]}
    return render_template('edit01.html', post=post)


# 从数据删除文章
@blog_bp.route('/<int:id>/delete', methods=['POST'])
@is_login
def delete(id):
    # 删除文章
    conn = sqlite3.connect('blog.db')
    cursor = conn.cursor()
    cursor.execute('DELETE FROM posts WHERE id = ?', (id,))
    conn.commit()
    conn.close()

    # 显示成功消息
    flash('文章已删除')
    return redirect(url_for('blog.index'))


import pandas as pd


# 词频画图
def bar_base(all_words) -> Bar:
    # all_words = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"
    #              "衬衫", "羊毛衫", "衬衫", "衬衫", "衬衫", "袜子"
    #              "羊毛衫", "羊毛衫", "雪纺衫", "裤子", "衬衫", "袜子"]
    words_counts = pd.Series(all_words).value_counts().head(10)
    words_counts = words_counts.to_dict()
    words_counts_key = list(words_counts.keys())
    words_counts_value = list(words_counts.values())

    c = (
        Bar()
        .add_xaxis(words_counts_key)
        .add_yaxis("统计一", words_counts_value)
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-基本示例", subtitle="词频分析"))
    )
    return c


import jieba
from wordcloud import WordCloud


# 获取文章分词
def cut_word(text):
    # 中文分词dpi,空格隔开每个词
    text = list(jieba.cut(text))
    print('text:', type(text), text)
    return text


# 词频统计
@blog_bp.route('/word_frequency', methods=['GET', 'POST'])
@is_login
def word_frequency():
    # 读取数据
    conn = sqlite3.connect('blog.db')
    cursor = conn.cursor()

    # 查询所有文章
    cursor.execute('SELECT id, title, content, created_at FROM posts ORDER BY created_at DESC')
    posts = cursor.fetchall()
    contents = [content for id, title, content, created_at in posts]
    print ('contents:', contents)

    # 创建停用词列表
    stopwords = [line.strip() for line in open('machine_learning/data/stopword/stopword.txt', encoding='UTF-8').readlines()]
    stopwords += ' '

    # 接收拆分后的数据
    data_new = []
    for sent in contents:
        data_new += cut_word(sent)
    print('data_new:', data_new)

    data_new_list = list(filter(None, (map(lambda x:x if x not in stopwords else '', data_new))))
    print ('data_new_list:', data_new_list)

    # 生成词云
    wordcloud = WordCloud(font_path="static/font/simkai.ttf", width=850, height=400).generate(' '.join(data_new_list))
    wordcloud.to_file('static/image/wordcloud_test_01.jpg')

    c = bar_base(data_new_list)
    return render_template('word_frequency.html', post=markupsafe.Markup(c.render_embed()))


import pickle
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2


# 读取存储的 sklearn 模型
def get_model():
    # 读取模型
    with open('machine_learning/model/clf.pickle', 'rb') as clf:
        model = pickle.load(clf)

    with open('machine_learning/model/count_vect.pickle', 'rb') as count_vect:
        count_vect = pickle.load(count_vect)

    with open('machine_learning/model/tfidf_trainformer.pickle', 'rb') as tfidf_trainformer:
        tfidf_trainformer = pickle.load(tfidf_trainformer)

    return model, count_vect, tfidf_trainformer

# 读取存储的伯努利模型
def get_model1():
    # 读取模型
    with open('machine_learning/model/train0.1_1.pickle', 'rb') as clf:
        model = pickle.load(clf)

    with open('machine_learning/model/train0.1_2.pickle', 'rb') as count_vect:
        count_vect = pickle.load(count_vect)

    with open('machine_learning/model/train0.1_3.pickle', 'rb') as tfidf_trainformer:
        tfidf_trainformer = pickle.load(tfidf_trainformer)

    return model, count_vect, tfidf_trainformer

# 读取存储的决策时模型
def get_model2():
    # 读取模型
    with open('machine_learning/model/train3.1.pickle', 'rb') as clf:
        model = pickle.load(clf)

    with open('machine_learning/model/train3.2.pickle', 'rb') as count_vect:
        count_vect = pickle.load(count_vect)

    with open('machine_learning/model/train3.3.pickle', 'rb') as tfidf_trainformer:
        tfidf_trainformer = pickle.load(tfidf_trainformer)

    return model, count_vect, tfidf_trainformer


# 获取分类模型的类别
def get_chinese_classifly():
    code_chinese_dict = {
        'news_story':'民生故事',
        'news_culture':'文化',
        'news_entertainment':'娱乐',
        'news_sports':'体育',
        'news_finance':'财经',
        'news_house':'房产',
        'news_car':'汽车',
        'news_edu':'教育',
        'news_tech':'科技',
        'news_military':'军事',
        'news_travel':'旅游',
        'news_world':'国际',
        'stock':'证券股票',

blog/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>博客管理系统（实验）</title>
  <link rel="stylesheet" href="../static/css/layui.css">
<!--  <link rel="stylesheet" href="../static/css/layui.mobile.css">-->
</head>

<body>
<div class="layui-layout layui-layout-admin">
  <div class="layui-header">
    <div class="layui-logo layui-hide-xs layui-bg-black">博客demo</div>
    <!-- 头部区域（可配合layui 已有的水平导航） -->
    <ul class="layui-nav layui-layout-left">
      <li class="layui-nav-item layui-hide-xs"><a href="{{ url_for('blog.index') }}">首页</a></li>
          <li class="layui-nav-item">
            <a href="javascript:;">常规</a>
          </li>
          <li class="layui-nav-item"><a href="">导航</a></li>
          <li class="layui-nav-item">
            <a href="javascript:;">子级</a>
            <dl class="layui-nav-child">
              <dd><a href="">菜单1</a></dd>
              <dd><a href="">菜单2</a></dd>
              <dd><a href="">菜单3</a></dd>
            </dl>
          </li>
          <li class="layui-nav-item">
            <a href="javascript:;">选项</a>
            <dl class="layui-nav-child">
              <dd><a href="">选项1</a></dd>
              <dd class="layui-this"><a href="">选项2</a></dd>
              <dd><a href="">选项3</a></dd>
            </dl>
          </li>
    </ul>


    <!--    登陆信息-->
    <ul class="layui-nav layui-layout-right">
      <li class="layui-nav-item layui-hide layui-show-md-inline-block">
        <a href="javascript:;">
          <img src="../static/image/logo.jpg" class="layui-nav-img">
          tester
        </a>
        <dl class="layui-nav-child">
          <dd><a href="">用户信息</a></dd>
          <dd><a href="/logout/">注销</a></dd>
        </dl>
      </li>

      <li class="layui-nav-item" lay-header-event="menuRight" lay-unselect>
        <a href="javascript:;">
          <i class="layui-icon layui-icon-more-vertical"></i>
        </a>
      </li>

    </ul>

  </div>

  <div class="layui-side layui-bg-black">
    <div class="layui-side-scroll">
      <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
      <ul class="layui-nav layui-nav-tree" lay-filter="test">
        <li class="layui-nav-item layui-nav-itemed">
          <a class="" href="javascript:;">文章管理</a>
          <dl class="layui-nav-child">
            <dd><a href="{{ url_for('blog.biaoge') }}">文章列表</a></dd>
            <dd><a href="{{ url_for('blog.create') }}">添加文章</a></dd>
{#            <dd><a href="{{ url_for('blog.find' ,title=post['title']) }}">查询文章</a></dd>#}
          </dl>
        </li>

{#        <li class="layui-nav-item">#}
          <li class="layui-nav-item layui-nav-itemed">
          <a href="javascript:;">文章分析</a>
          <dl class="layui-nav-child">
            <dd><a href="{{ url_for('blog.word_frequency') }}">词频分析</a></dd>
            <dd><a href="{{ url_for('blog.categories') }}">文章分类</a></dd>
            <dd><a href="{{ url_for('blog.categories1') }}">文章分类(伯努利)</a></dd>
            <dd><a href="{{ url_for('blog.categories2') }}">文章分类(决策树)</a></dd>
            <dd><a href="{{ url_for('blog.categories_dl') }}">深度学习</a></dd>
          </dl>
        </li>

{#        <li class="layui-nav-item"><a href="javascript:;">用户管理</a></li>#}
{#            <dl class="layui-nav-child">#}
{#                <dd><a href="{{ url_for('blog.login') }}">登录</a></dd>#}
{#                <dd><a href="{{ url_for('blog.register') }}">注册</a></dd>#}
{#                <dd><a href="/logout/" id="zhuxiao">注销</a></dd>#}
{#            </dl>#}
        <li class="layui-nav-item layui-nav-itemed">
            <a href="javascript:;">用户管理</a>
            <dl class="layui-nav-child">
                <dd><a href="{{ url_for('blog.login') }}">登录</a></dd>
                <dd><a href="{{ url_for('blog.register') }}">注册</a></dd>
                <dd><a href="/logout/" id="zhuxiao">注销</a></dd>
            </dl>
        </li>
        <li class="layui-nav-item"><a href="{{ url_for('blog.about') }}">about</a></li>

      </ul>
    </div>
  </div>

  <div class="layui-body">
    <!-- 内容主体区域 -->

<!--    <nav>-->
<!--        <ul>-->
<!--            <li><a href="{{ url_for('blog.index') }}">首页</a></li>-->
<!--            <li><a href="{{ url_for('blog.create') }}">添加文章</a></li>-->
<!--        </ul>-->
<!--    </nav>-->

    <div style="padding: 15px;">

      {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

    {% endwith %}
    {% block content %}{% endblock %}

    </div>

  </div>

  <div class="layui-footer">
    <!-- 底部固定区域 -->
    底部固定区域
  </div>
</div>

<script src="../static/layui.js"></script>
<script src="../static/layedit.js"></script>

<script>
//JS
layui.use(['element', 'layer', 'util', 'layedit', 'form'], function(){
  var element = layui.element
  ,layer = layui.layer
  ,util = layui.util
  ,$ = layui.$;

  //头部事件
  util.event('lay-header-event', {
    //左侧菜单事件
    menuLeft: function(othis){
      layer.msg('展开左侧菜单的操作', {icon: 0});
    }
    ,menuRight: function(){
      layer.open({
        type: 1
        ,content: '<div style="padding: 15px;">处理右侧面板的操作</div>'
        ,area: ['260px', '100%']
        ,offset: 'rt' //右上角
        ,anim: 5
        ,shadeClose: true
      });
    }
  });

  var layedit = layui.layedit
                ,$ = layui.jquery;
  var layedit_2 = layui.layedit
                ,$ = layui.jquery;


  //自定义工具栏
  layedit.build('LAY_demo1'
      ,{tool: [
        'strong' //加粗
        ,'italic' //斜体
        ,'underline' //下划线
        ,'del' //删除线
        ,'|' //分割线
        ,'left' //左对齐
        ,'center' //居中对齐
        ,'face' //表情
        ,'help' //帮助
      ]
      ,height: 280 //设置编辑器高度
      }
  );
  layedit_2.build('LAY_demo2'
      ,{
      height: 280 //设置编辑器高度
<!--      ,hideTool: False-->
      }
  );


});
</script>
</body>
<style type="text/css">
    body{
	    background: url("../static/image/sun.jpg") no-repeat center center fixed;
        -webkit-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
	}
</style>
</html>

blog/templates/base01.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>博客管理系统（实验）</title>
  <link rel="stylesheet" href="../static/css/layui.css">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <style>
    body{margin: 10px;}
    .demo-carousel{height: 200px; line-height: 200px; text-align: center;}
  </style>
</head>

{#<body background="../static/image/sun.jpg">#}

<script src="../static/layui.js"  ></script>
<script src="../static/layedit.js"  ></script>
<script src="../static/layer/layer.js" ></script>
<script src="../static/jquery.min.js"></script>
<div class="layui-layout layui-layout-admin">
  <div class="layui-header">
    <div class="layui-logo layui-hide-xs layui-bg-black">博客demo</div>
    <!-- 头部区域（可配合layui 已有的水平导航） -->
    <ul class="layui-nav layui-layout-left">
      <li class="layui-nav-item layui-hide-xs"><a href="{{ url_for('blog.index') }}">首页</a></li>
          <li class="layui-nav-item">
            <a href="javascript:;">常规</a>
          </li>
          <li class="layui-nav-item"><a href="">导航</a></li>
          <li class="layui-nav-item">
            <a href="javascript:;">子级</a>
            <dl class="layui-nav-child">
              <dd><a href="">菜单1</a></dd>
              <dd><a href="">菜单2</a></dd>
              <dd><a href="">菜单3</a></dd>
            </dl>
          </li>
          <li class="layui-nav-item">
            <a href="javascript:;">选项</a>
            <dl class="layui-nav-child">
              <dd><a href="">选项1</a></dd>
              <dd class="layui-this"><a href="">选项2</a></dd>
              <dd><a href="">选项3</a></dd>
            </dl>
          </li>
    </ul>


    <!--    登陆信息-->
    <ul class="layui-nav layui-layout-right">
      <li class="layui-nav-item layui-hide layui-show-md-inline-block">
        <a href="javascript:;">
          <img src="../static/image/logo.jpg" class="layui-nav-img">
        </a>
        <dl class="layui-nav-child">
          <dd><a href="">用户信息</a></dd>
          <dd><a href="/logout/">注销</a></dd>
        </dl>
      </li>

      <li class="layui-nav-item" lay-header-event="menuRight" lay-unselect>
        <a href="javascript:;">
          <i class="layui-icon layui-icon-more-vertical"></i>
        </a>
      </li>

    </ul>

  </div>

  <div class="layui-side layui-bg-black">
    <div class="layui-side-scroll">
      <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
      <ul class="layui-nav layui-nav-tree" lay-filter="test">
        <li class="layui-nav-item layui-nav-itemed">
          <a class="" href="javascript:;">文章管理</a>
          <dl class="layui-nav-child">
            <dd><a href="{{ url_for('blog.biaoge') }}">文章列表</a></dd>
            <dd><a href="{{ url_for('blog.create') }}">添加文章</a></dd>
          </dl>
        </li>

        <li class="layui-nav-item">
          <a href="javascript:;">文章分析</a>
          <dl class="layui-nav-child">
{#            <dd><a href="{{ url_for('blog.word_frequency') }}">词频分析</a></dd>#}
{#            <dd><a href="{{ url_for('blog.categories') }}">文章分类</a></dd>#}
            <dd><a href="{{ url_for('blog.word_frequency') }}">词频分析</a></dd>
            <dd><a href="{{ url_for('blog.categories') }}">文章分类</a></dd>
            <dd><a href="{{ url_for('blog.categories1') }}">文章分类(伯努利)</a></dd>
            <dd><a href="{{ url_for('blog.categories2') }}">文章分类(决策树)</a></dd>
            <dd><a href="{{ url_for('blog.categories_dl') }}">深度学习</a></dd>
          </dl>
        </li>

        <li class="layui-nav-item">
            <a href="javascript:;">用户管理</a>
            <dl class="layui-nav-child">
                <dd><a href="{{ url_for('blog.login') }}">登录</a></dd>
                <dd><a href="{{ url_for('blog.register') }}">注册</a></dd>
                <dd><a href="/logout/" id="zhuxiao">注销</a></dd>
            </dl>
        </li>
        <li class="layui-nav-item"><a href="{{ url_for('blog.about') }}">about</a></li>

      </ul>
    </div>
  </div>

  <div class="layui-body">
    <!-- 内容主体区域 -->

<!--    <nav>-->
<!--        <ul>-->
<!--            <li><a href="{{ url_for('blog.index') }}">首页</a></li>-->
<!--            <li><a href="{{ url_for('blog.create') }}">添加文章</a></li>-->
<!--        </ul>-->
<!--    </nav>-->

    <div style="padding: 15px;">

      {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

    {% endwith %}
    {% block content %}{% endblock %}

    </div>

  </div>

</div>
<script src="../static/layui.js"></script>
<script src="../static/layer/layer.js" ></script>
<script src="../static/jquery.min.js"></script>
<script>
//JS
layui.use(['element', 'layer', 'util' ,'rate' ,'layedit' ,'form'], function(){
  var element = layui.element
  ,layer = layui.layer
  ,util = layui.util
  ,rate = layui.rate
  ,$ = layui.$;

  //头部事件
  util.event('lay-header-event', {
    //左侧菜单事件
    menuLeft: function(othis){
      layer.msg('展开左侧菜单的操作', {icon: 0});
    }
    ,menuRight: function(){
      layer.open({
        type: 1
        ,content: '<div style="padding: 15px;">处理右侧面板的操作</div>'
        ,area: ['260px', '100%']
        ,offset: 'rt' //右上角
        ,anim: 5
        ,shadeClose: true
      });
    }
  });

  var layedit = layui.layedit
                ,$ = layui.jquery;
  var layedit_2 = layui.layedit
                ,$ = layui.jquery;

    //自定义工具栏
  layedit.build('LAY_demo1'
      ,{tool: [
        'strong' //加粗
        ,'italic' //斜体
        ,'underline' //下划线
        ,'del' //删除线
        ,'|' //分割线
        ,'left' //左对齐
        ,'center' //居中对齐
        ,'face' //表情
        ,'help' //帮助
      ]
      ,height: 280 //设置编辑器高度
      }
  );
  layedit_2.build('LAY_demo2'
      ,{
      height: 280 //设置编辑器高度
<!--      ,hideTool: False-->
      }
  );


});
</script>
</body>

<style type="text/css">
    body{
	    background: url("../static/image/sun.jpg") no-repeat center center fixed;
        -webkit-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
	}
</style>

</html>

blog/templates/biaoge.html
{% extends 'base.html' %}

{#{% block title %}文章列表{% endblock %}#}
{##}
{% block content %}
{#<!--<h1>文章列表</h1>-->#}
{##}
{##}
{##}
{#{% for post in posts %}#}

<div class="layui-form">
  <table class="layui-table">
    <colgroup>
      <col width="150">
      <col width="150">
      <col width="200">
      <col>
    </colgroup>
        <form action="{{ url_for('blog.find') }}" method="post">
            <div>
                <label for="title">标题：</label>
                <input type="text" id="title" name="title" required>
            </div>

            <button type="submit">查询</button>
        </form>
    <thead>
      <tr>
        <th>标题</th>
        <th>创建时间</th>
        <th>内容</th>
        <th>添加</th>
        <th>删除</th>

      </tr>
    </thead>
    {% for post in posts %}

    <tbody>



      <tr>
        <td><a href="{{ url_for('blog.show', id=post['id']) }}"> {{ post['title'] }} </a></td>
        <td><p style="font-size:2px"><time datetime="{{ post['created_at'] }}"> {{ post['created_at'] }} </time></p></td>
        <td><p style="font-size:20px"> {{ post['content'][:7] }} ...</p></td>
        <td width="10%">
{#          <form action="{{ url_for('blog.edit', id=post['id']) }}" method="POST" class="container">#}
{#            <input type="hidden" value="{{ post.id }}" name="id">#}
{#            <input type="submit" class="layui-btn layui-btn-primary" value="删除文章">#}
{#              #}
{#          </form>#}
        <button type="submit" class="layui-btn layui-btn-primary">
        <a href="{{ url_for('blog.edit', id=post['id']) }}">编辑文章</a>
        </button>
        </td>
        <td width="10%">
          <form action="{{ url_for('blog.delete', id=post['id']) }}" method="POST" class="container">
            <input type="hidden" value="{{ post.id }}" name="id">
            <input type="submit" class="layui-btn layui-btn-primary" value="删除文章">
          </form>
        </td>
      </tr>
    </tbody>
    {% else %}
    <p>暂无文章</p>
    {% endfor %}
{#    {% endblock %}#}
  </table>
</div>

<script src="../static/layui.js" charset="utf-8"></script>
<!-- 注意：如果你直接复制所有代码到本地，上述 JS 路径需要改成你本地的 -->
<script>

</script>


{#{% else %}#}
{#    <p>暂无文章</p>#}
{#{% endfor %}#}
{% endblock %}


blog/templates/create.html
<!-- create.html -->
{% extends 'base.html' %}

{% block title %}添加文章{% endblock %}

{% block content %}
<h1>添加文章</h1>
<form action="{{ url_for('blog.create') }}" method="post">

    <div>
        <label for="title">标题：</label>
        <input type="text" id="title" name="title" required>
    </div>
{#    <div>#}
{#        <label for="content">内容：</label>#}
{#        <textarea rows="10" cols="50" id="content" name="content" required></textarea>#}
{#    </div>#}
        <div>
        <label for="LAY_demo1">内容：</label>
<!--        <textarea id="LAY_demo2" class="layui-textarea">-->
        <textarea rows="100" cols="50" class="layui-textarea" id="LAY_demo1" name="content" required>
        </textarea>
    </div>
    <button type="submit">添加文章</button>


</form>

{% endblock %}
